### ISSUE TITLE
403 Forbidden

### ISSUE THREAD

**Issue by Agmes47** [jessfin/nssign#2]
按照 Readme 中的来做了，但是返回了 403 响应码和html界面，是我的问题吗？
我在里面加了一行 print(response.status_code) 来打印响应码。
```
$ python3 main.py
403
Traceback (most recent call last):
  File "/home/userer/nssign/main.py", line 62, in <module>
    data = json.loads(response.text)
  File "/usr/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by jessfin** [comment]
> 按照 Readme 中的来做了，但是返回了 403 响应码和html界面，是我的问题吗？ 我在里面加了一行 print(response.status_code) 来打印响应码。
> 
> ```
> $ python3 main.py
> 403
> Traceback (most recent call last):
>   File "/home/userer/nssign/main.py", line 62, in <module>
>     data = json.loads(response.text)
>   File "/usr/lib/python3.9/json/__init__.py", line 346, in loads
>     return _default_decoder.decode(s)
>   File "/usr/lib/python3.9/json/decoder.py", line 337, in decode
>     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
>   File "/usr/lib/python3.9/json/decoder.py", line 355, in raw_decode
>     raise JSONDecodeError("Expecting value", s, err.value) from None
> json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
> ```

已经修复，拉最新的代码

**Comment by Agmes47** [comment]
测试成功，谢谢你！
